name: Insomnia Run
description: Run Insomnia Collections & Tests using the Inso CLI with PR comment reporting.
author: Sourab Kanthavar <@scarowar>

branding:
  icon: terminal
  color: purple

inputs:
  command:
    description: 'The command to run: "test" or "collection".'
    required: true
    type: choice
    options:
      - test
      - collection

  working-directory:
    description: "Path to Insomnia export file or .insomnia directory."
    required: true

  github-token:
    description: "GitHub token for posting PR comments. Uses GITHUB_TOKEN if not provided."
    required: false

  inso-version:
    description: "Version of Inso CLI to use."
    required: false
    default: "12.2.0"

  identifier:
    required: false
  environment:
    required: false

  request-name-pattern:
    required: false
  item:
    required: false
  globals:
    required: false
  delay-request:
    required: false
  iteration-count:
    required: false
  iteration-data:
    required: false
  env-var:
    required: false

  test-name-pattern:
    required: false
  keep-file:
    required: false
    default: "false"

  bail:
    required: false
    default: "false"
  request-timeout:
    required: false
  disable-cert-validation:
    required: false
    default: "false"
  https-proxy:
    required: false
  http-proxy:
    required: false
  no-proxy:
    required: false
  data-folders:
    required: false
  verbose:
    required: false
    default: "false"

  pr-comment:
    required: false
    default: "true"
  fail-on-error:
    required: false
    default: "true"

outputs:
  markdown:
    value: ${{ steps.run-cli.outputs.markdown }}
  exit-code:
    value: ${{ steps.run-cli.outputs.exit-code }}

runs:
  using: composite
  steps:
    - name: 🧰 Setup Inso CLI
      shell: bash
      run: |
        INSO_VERSION="${{ inputs.inso-version }}"
        echo "Installing inso version ${INSO_VERSION}..."
        curl -sL "https://github.com/Kong/insomnia/releases/download/core%40${INSO_VERSION}/inso-linux-x64-${INSO_VERSION}.tar.xz" -o /tmp/inso.tar.xz
        mkdir -p /tmp/inso
        tar -xJf /tmp/inso.tar.xz -C /tmp/inso
        sudo mv /tmp/inso/inso /usr/local/bin/inso
        sudo chmod +x /usr/local/bin/inso
        inso --version

    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ">=3.10"

    - name: 📦 Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867

    - name: 🔧 Install insomnia-run
      shell: bash
      run: uv pip install --system "$GITHUB_ACTION_PATH"

    - name: 🚀 Run Insomnia
      id: run-cli
      shell: bash
      env:
        COMMAND: ${{ inputs.command }}
        WORKING_DIR: ${{ inputs.working-directory }}
        IDENTIFIER: ${{ inputs.identifier }}
        ENVIRONMENT: ${{ inputs.environment }}

        REQUEST_NAME_PATTERN: ${{ inputs.request-name-pattern }}
        ITEM: ${{ inputs.item }}
        GLOBALS: ${{ inputs.globals }}
        DELAY_REQUEST: ${{ inputs.delay-request }}
        ITERATION_COUNT: ${{ inputs.iteration-count }}
        ITERATION_DATA: ${{ inputs.iteration-data }}
        ENV_VAR: ${{ inputs.env-var }}

        TEST_NAME_PATTERN: ${{ inputs.test-name-pattern }}
        KEEP_FILE: ${{ inputs.keep-file }}

        BAIL: ${{ inputs.bail }}
        REQUEST_TIMEOUT: ${{ inputs.request-timeout }}
        DISABLE_CERT_VALIDATION: ${{ inputs.disable-cert-validation }}

        HTTPS_PROXY: ${{ inputs.https-proxy }}
        HTTP_PROXY: ${{ inputs.http-proxy }}
        NO_PROXY: ${{ inputs.no-proxy }}
        DATA_FOLDERS: ${{ inputs.data-folders }}
        VERBOSE: ${{ inputs.verbose }}

        WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      run: |
        set +e

        if [[ "$COMMAND" == "collection" ]]; then
          CMD=(insomnia-run run-collection)
        else
          CMD=(insomnia-run run-test)
        fi

        CMD+=(--working-dir "$WORKING_DIR")
        [[ -n "$IDENTIFIER" ]] && CMD+=(--identifier "$IDENTIFIER")
        [[ -n "$ENVIRONMENT" ]] && CMD+=(--env "$ENVIRONMENT")

        if [[ "$COMMAND" == "collection" ]]; then
          [[ -n "$REQUEST_NAME_PATTERN" ]] && CMD+=(--request-name-pattern "$REQUEST_NAME_PATTERN")
          [[ -n "$GLOBALS" ]] && CMD+=(--globals "$GLOBALS")
          [[ -n "$DELAY_REQUEST" ]] && CMD+=(--delay-request "$DELAY_REQUEST")
          [[ -n "$ITERATION_COUNT" ]] && CMD+=(--iteration-count "$ITERATION_COUNT")
          [[ -n "$ITERATION_DATA" ]] && CMD+=(--iteration-data "$ITERATION_DATA")

          if [[ -n "$ITEM" ]]; then
            IFS=',' read -ra ITEMS <<< "$ITEM"
            for i in "${ITEMS[@]}"; do
              CMD+=(--item "$i")
            done
          fi

          if [[ -n "$ENV_VAR" ]]; then
            while IFS= read -r line; do
              [[ -n "$line" ]] && CMD+=(--env-var "$line")
            done <<< "$ENV_VAR"
          fi
        fi

        if [[ "$COMMAND" == "test" ]]; then
          [[ -n "$TEST_NAME_PATTERN" ]] && CMD+=(--test-name-pattern "$TEST_NAME_PATTERN")
          [[ "$KEEP_FILE" == "true" ]] && CMD+=(--keep-file)
        fi

        [[ "$BAIL" == "true" ]] && CMD+=(--bail)
        [[ -n "$REQUEST_TIMEOUT" ]] && CMD+=(--request-timeout "$REQUEST_TIMEOUT")
        [[ "$DISABLE_CERT_VALIDATION" == "true" ]] && CMD+=(--disable-cert-validation)
        [[ -n "$HTTPS_PROXY" ]] && CMD+=(--https-proxy "$HTTPS_PROXY")
        [[ -n "$HTTP_PROXY" ]] && CMD+=(--http-proxy "$HTTP_PROXY")
        [[ -n "$NO_PROXY" ]] && CMD+=(--no-proxy "$NO_PROXY")
        [[ "$VERBOSE" == "true" ]] && CMD+=(--verbose)

        if [[ -n "$DATA_FOLDERS" ]]; then
          IFS=',' read -ra FOLDERS <<< "$DATA_FOLDERS"
          for f in "${FOLDERS[@]}"; do
            CMD+=(--data-folders "$f")
          done
        fi

        CMD+=(--workflow-url "$WORKFLOW_URL")

        echo "::group::Running Insomnia"
        MARKDOWN="$("${CMD[@]}")"
        EXIT_CODE=$?
        echo "::endgroup::"

        echo "exit-code=$EXIT_CODE" >> "$GITHUB_OUTPUT"

        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        {
          echo "markdown<<$EOF"
          echo "$MARKDOWN"
          echo "$EOF"
        } >> "$GITHUB_OUTPUT"

        echo "$MARKDOWN" >> "$GITHUB_STEP_SUMMARY"
        exit 0

    - name: 💬 Post PR Comment
      if: inputs.pr-comment == 'true' && github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.github-token || github.token }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.run-cli.outputs.markdown }}

    - name: ❌ Check for Failures
      if: inputs.fail-on-error == 'true' && steps.run-cli.outputs.exit-code != '0'
      shell: bash
      run: |
        echo "::error::Tests failed. See the report above for details."
        exit 1
