name: Insomnia Run
description: Run Insomnia Collections & Tests using the Inso CLI with PR comment reporting.
author: Sourab Kanthavar <@scarowar>

branding:
  icon: terminal
  color: purple

inputs:
  execution-timeout:
    description: "Timeout for entire execution in seconds. Default is 300. Increase for large collections or slow APIs."
    required: false
    default: "300"
  command:
    description: 'The command to run: "test" or "collection".'
    required: true

  working-directory:
    description: "Path to Insomnia export file or .insomnia directory."
    required: true

  github-token:
    description: "GitHub token for posting PR comments. Uses GITHUB_TOKEN if not provided."
    required: false

  inso-version:
    description: "Version of Inso CLI to use."
    required: false
    default: "12.2.0"

  identifier:
    description: "Collection name, test suite name, or workspace ID to run."
    required: false
  environment:
    description: "Insomnia environment name to use."
    required: false

  request-name-pattern:
    description: "Regex pattern to filter requests by name (collection only)."
    required: false
  item:
    description: "Specific request or folder IDs to run, comma-separated."
    required: false
  globals:
    description: "Path to global environment file or ID."
    required: false
  delay-request:
    description: "Delay between requests in milliseconds."
    required: false
  iteration-count:
    description: "Number of times to iterate through the collection."
    required: false
  iteration-data:
    description: "Path to CSV or JSON data file for iterations."
    required: false
  env-var:
    description: "Environment variables in KEY=VALUE format, one per line."
    required: false

  test-name-pattern:
    description: "Regex pattern to filter tests by name (test only)."
    required: false
  keep-file:
    description: "Keep the generated test file after execution."
    required: false
    default: "false"

  bail:
    description: "Stop execution on first failure."
    required: false
    default: "false"
  request-timeout:
    description: "Request timeout in milliseconds."
    required: false
  disable-cert-validation:
    description: "Disable SSL certificate validation."
    required: false
    default: "false"
  https-proxy:
    description: "HTTPS proxy URL."
    required: false
  http-proxy:
    description: "HTTP proxy URL."
    required: false
  no-proxy:
    description: "Comma-separated list of hosts to bypass proxy."
    required: false
  data-folders:
    description: "Folders that Insomnia can access for file references."
    required: false
  verbose:
    description: "Enable verbose logging."
    required: false
    default: "false"

  pr-comment:
    description: "Post test results as a PR comment."
    required: false
    default: "true"
  fail-on-error:
    description: "Fail the workflow if tests fail."
    required: false
    default: "true"

outputs:
  markdown:
    value: ${{ steps.run-cli.outputs.markdown }}
  exit-code:
    value: ${{ steps.run-cli.outputs.exit-code }}

runs:
  using: composite
  steps:
    - name: 🧰 Setup Inso CLI
      shell: bash
      run: |
        INSO_VERSION="${{ inputs.inso-version }}"
        echo "Installing inso version ${INSO_VERSION}..."
        curl -sL "https://github.com/Kong/insomnia/releases/download/core%40${INSO_VERSION}/inso-linux-x64-${INSO_VERSION}.tar.xz" -o /tmp/inso.tar.xz
        mkdir -p /tmp/inso
        tar -xJf /tmp/inso.tar.xz -C /tmp/inso
        sudo mv /tmp/inso/inso /usr/local/bin/inso
        sudo chmod +x /usr/local/bin/inso
        inso --version

    - name: ✅ Verify Python Requirements
      shell: bash
      run: |
        set +e

        # Check if Python 3 is available
        if ! command -v python3 &> /dev/null; then
          echo "::error::Python 3 is not installed or not in PATH"
          echo "::error::insomnia-run requires Python 3.10 or higher"
          echo "::error::GitHub-hosted runners have Python pre-installed. If using a self-hosted runner, please install Python 3.10+."
          exit 1
        fi

        # Check Python version requirement
        python3 - <<'EOF'
        import sys
        if sys.version_info < (3, 10):
            print("::error::insomnia-run requires Python 3.10 or higher")
            print(f"::error::Current version: {sys.version}")
            print("::error::GitHub-hosted runners provide Python 3.10+. Consider using a newer runner image or upgrading Python.")
            sys.exit(1)
        print(f"Using Python {sys.version.split()[0]}")
        EOF

        if [[ $? -ne 0 ]]; then
          exit 1
        fi

    - name: 📦 Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867

    - name: 🔧 Install insomnia-run
      shell: bash
      run: uv pip install --system "$GITHUB_ACTION_PATH"

    - name: 🚀 Run Insomnia
      id: run-cli
      shell: bash
      env:
        EXECUTION_TIMEOUT: ${{ inputs.execution-timeout }}
        COMMAND: ${{ inputs.command }}
        WORKING_DIR: ${{ inputs.working-directory }}
        IDENTIFIER: ${{ inputs.identifier }}
        ENVIRONMENT: ${{ inputs.environment }}

        REQUEST_NAME_PATTERN: ${{ inputs.request-name-pattern }}
        ITEM: ${{ inputs.item }}
        GLOBALS: ${{ inputs.globals }}
        DELAY_REQUEST: ${{ inputs.delay-request }}
        ITERATION_COUNT: ${{ inputs.iteration-count }}
        ITERATION_DATA: ${{ inputs.iteration-data }}
        ENV_VAR: ${{ inputs.env-var }}

        TEST_NAME_PATTERN: ${{ inputs.test-name-pattern }}
        KEEP_FILE: ${{ inputs.keep-file }}

        BAIL: ${{ inputs.bail }}
        REQUEST_TIMEOUT: ${{ inputs.request-timeout }}
        DISABLE_CERT_VALIDATION: ${{ inputs.disable-cert-validation }}

        HTTPS_PROXY: ${{ inputs.https-proxy }}
        HTTP_PROXY: ${{ inputs.http-proxy }}
        NO_PROXY: ${{ inputs.no-proxy }}
        DATA_FOLDERS: ${{ inputs.data-folders }}
        VERBOSE: ${{ inputs.verbose }}

        WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      run: |
        set +e

        # Add Python bin directory to PATH to ensure installed scripts are available
        PYTHON_BIN_DIR="$(python3 -c 'import sys; import os; print(os.path.dirname(sys.executable))' 2>&1)"
        if [[ $? -ne 0 ]] || [[ -z "$PYTHON_BIN_DIR" ]]; then
          echo "::error::Failed to determine Python bin directory"
          echo "::error::Python detection output: $PYTHON_BIN_DIR"
          exit 1
        fi

        export PATH="$PYTHON_BIN_DIR:$PATH"

        # Verify insomnia-run is available
        if ! command -v insomnia-run &> /dev/null; then
          echo "::error::insomnia-run command not found after installation"
          echo "::error::Python bin directory: $PYTHON_BIN_DIR"
          echo "::error::Current PATH: $PATH"
          echo "::error::This may indicate an installation issue. Please report this at https://github.com/scarowar/insomnia-run/issues"
          exit 1
        fi

        if [[ "$COMMAND" != "collection" && "$COMMAND" != "test" ]]; then
          echo "::error::Invalid command '$COMMAND'. Must be 'collection' or 'test'."
          exit 1
        fi

        if [[ "$COMMAND" == "collection" ]]; then
          CMD=(insomnia-run run-collection)
        else
          CMD=(insomnia-run run-test)
        fi

        CMD+=(--working-dir "$WORKING_DIR")

        # Add execution-timeout if set
        if [[ -n "$EXECUTION_TIMEOUT" ]]; then
          CMD+=(--execution-timeout "$EXECUTION_TIMEOUT")
        fi

        [[ -n "$IDENTIFIER" ]] && CMD+=(--identifier "$IDENTIFIER")
        [[ -n "$ENVIRONMENT" ]] && CMD+=(--env "$ENVIRONMENT")

        if [[ "$COMMAND" == "collection" ]]; then
          [[ -n "$REQUEST_NAME_PATTERN" ]] && CMD+=(--request-name-pattern "$REQUEST_NAME_PATTERN")
          [[ -n "$GLOBALS" ]] && CMD+=(--globals "$GLOBALS")
          [[ -n "$DELAY_REQUEST" ]] && CMD+=(--delay-request "$DELAY_REQUEST")
          [[ -n "$ITERATION_COUNT" ]] && CMD+=(--iteration-count "$ITERATION_COUNT")
          [[ -n "$ITERATION_DATA" ]] && CMD+=(--iteration-data "$ITERATION_DATA")

          if [[ -n "$ITEM" ]]; then
            IFS=',' read -ra ITEMS <<< "$ITEM"
            for i in "${ITEMS[@]}"; do
              i="$(echo "$i" | xargs)"
              CMD+=(--item "$i")
            done
          fi

          if [[ -n "$ENV_VAR" ]]; then
            while IFS= read -r line; do
              [[ -n "$line" ]] && CMD+=(--env-var "$line")
            done <<< "$ENV_VAR"
          fi
        fi

        if [[ "$COMMAND" == "test" ]]; then
          [[ -n "$TEST_NAME_PATTERN" ]] && CMD+=(--test-name-pattern "$TEST_NAME_PATTERN")
          [[ "$KEEP_FILE" == "true" ]] && CMD+=(--keep-file)
        fi

        [[ "$BAIL" == "true" ]] && CMD+=(--bail)
        [[ -n "$REQUEST_TIMEOUT" ]] && CMD+=(--request-timeout "$REQUEST_TIMEOUT")
        [[ "$DISABLE_CERT_VALIDATION" == "true" ]] && CMD+=(--disable-cert-validation)
        [[ -n "$HTTPS_PROXY" ]] && CMD+=(--https-proxy "$HTTPS_PROXY")
        [[ -n "$HTTP_PROXY" ]] && CMD+=(--http-proxy "$HTTP_PROXY")
        [[ -n "$NO_PROXY" ]] && CMD+=(--no-proxy "$NO_PROXY")
        [[ "$VERBOSE" == "true" ]] && CMD+=(--verbose)

        if [[ -n "$DATA_FOLDERS" ]]; then
          IFS=',' read -ra FOLDERS <<< "$DATA_FOLDERS"
          for f in "${FOLDERS[@]}"; do
            CMD+=(--data-folders "$f")
          done
        fi

        CMD+=(--workflow-url "$WORKFLOW_URL")

        echo "::group::Running Insomnia"
        echo "Executing: ${CMD[*]}"
        MARKDOWN="$("${CMD[@]}")"
        EXIT_CODE=$?
        echo "::endgroup::"

        echo "exit-code=$EXIT_CODE" >> "$GITHUB_OUTPUT"

        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        {
          echo "markdown<<$EOF"
          echo "$MARKDOWN"
          echo "$EOF"
        } >> "$GITHUB_OUTPUT"

        echo "$MARKDOWN" >> "$GITHUB_STEP_SUMMARY"
        exit 0

    - name: 💬 Post PR Comment
      if: inputs.pr-comment == 'true' && github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v5
      with:
        token: ${{ inputs.github-token || github.token }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.run-cli.outputs.markdown }}

    - name: ❌ Check for Failures
      if: inputs.fail-on-error == 'true' && steps.run-cli.outputs.exit-code != '0'
      shell: bash
      run: |
        echo "::error::Tests failed. See the report above for details."
        exit 1
